package com.coachify.coaches.exception;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
public class GlobalExceptionHandler {

	private static final Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandler.class);
	
	@ExceptionHandler(CoachAlreadyExistsException.class)
	public ResponseEntity<Object> handleCustomerAlreadyExistsException(CoachAlreadyExistsException ex){
		return ResponseEntity
                .status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(ex.getMessage());
		
	}
	
	@ExceptionHandler(CoachNotFoundException.class)
	public ResponseEntity<Object> handleCustomerNotFoundException(CoachNotFoundException ex){
		return ResponseEntity
                .status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(ex.getMessage());
	}
	
	@ExceptionHandler(LoginCoachException.class)
	public ResponseEntity<Object> handleLoginCustomerException(LoginCoachException ex){
		return ResponseEntity
                .status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(ex.getMessage());
	}
	
	@ExceptionHandler(CoachException.class)
	public ResponseEntity<Object> handleCustomerException(CoachException ex){
		return ResponseEntity
                .status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(ex.getMessage());
	}
	
	
}
